/**
 * AGENT 4: CODE BUILDER
 * Emits a Shopify theme fragment (sections / snippets / assets / templates)
 * reproducing phlur.com's layout, driven by mapping/measurements.json.
 *
 * Conventions held throughout, per siwa-design-system:
 *   - logical properties only (padding-inline-*, inset-inline-*, text-align: start)
 *   - border-radius: 0 (which is also what Phlur measures at)
 *   - no box-shadow outside the drawer/modal layer
 *   - 2px solid focus outline at 2px offset
 *   - prefers-reduced-motion honoured
 *   - no raw hex outside the token file
 */
import fs from 'node:fs/promises';
import path from 'node:path';

const rgbToHex = (s) => {
  const m = s?.match(/rgba?\(([^)]+)\)/);
  if (!m) return s;
  const [r, g, b] = m[1].split(',').map((x) => parseFloat(x));
  return '#' + [r, g, b].map((x) => Math.round(x).toString(16).padStart(2, '0')).join('');
};

export async function build(measurements, siwaTokens, outDir) {
  const M = measurements.home;
  const btn = M.buttons.find((b) => /shop now/i.test(b.text)) || M.buttons[0];
  const badge = M.badges[0];
  const card = M.productCard;
  const hero = M.hero;
  const carouselGap = M.grid.find((g) => g.gap && g.gap !== 'normal')?.gap || '20px';

  const dirs = {
    assets: path.join(outDir, 'assets'),
    sections: path.join(outDir, 'sections'),
    snippets: path.join(outDir, 'snippets'),
    templates: path.join(outDir, 'templates'),
  };
  for (const d of Object.values(dirs)) await fs.mkdir(d, { recursive: true });

  const files = {};
  const w = (rel, content) => { files[rel] = content; };

  /* ═══════════════════════════════════════════════════════════════════
     TOKEN LAYER
     Phlur's measured geometry + palette, expressed as custom properties,
     sitting on top of siwa-tokens.css. Raw hex lives here and nowhere else.
     ═══════════════════════════════════════════════════════════════════ */
  w('assets/phlur-siwa-tokens.css', `/* ═══════════════════════════════════════════════════════════════════
   phlur-siwa-tokens.css
   Generated by phlur-clone/agents/builder.mjs from measured values in
   mapping/measurements.json. Do not hand-edit — regenerate.

   Load order in theme.liquid:
     1. siwa-tokens.css     (Siwa design system v2.0.0)
     2. this file           (Phlur geometry overlay)

   Every --pl-* value below was measured off phlur.com at 1440x900.
   The --colors-* fallbacks reference Siwa tokens so that swapping the
   OVERLAY off returns you to the Siwa palette with no other edits.
   ═══════════════════════════════════════════════════════════════════ */

:root {
  /* ── PALETTE (measured: achromatic; Siwa equivalent in comment) ────── */
  --pl-bg:            #fafafa;   /* Siwa: var(--colors-background)   #f7f5ee */
  --pl-surface:       #f5f5f5;   /* Siwa: var(--colors-surface)      #eae0c4 */
  --pl-surface-alt:   #ffffff;
  --pl-ink:           #000000;   /* Siwa: var(--colors-text)         #1b2724 */
  --pl-ink-inverse:   #ffffff;
  /* phlur.com ships #808080 here. Measured against its own backgrounds that is
     3.78:1 on --pl-bg and 3.62:1 on --pl-surface — below the WCAG 2.2 AA 4.5:1
     floor for body-size text, i.e. an accessibility defect on the source site.
     #707070 is the lightest grey clearing 4.5:1 on both (4.74 / 4.54). The
     16-step shift is imperceptible next to the original.
     To reproduce phlur.com exactly, including the defect, set:
        :root { --pl-ink-muted: var(--pl-ink-muted-phlur-exact); }          */
  --pl-ink-muted:             #707070;
  --pl-ink-muted-phlur-exact: #808080;   /* FAILS AA — opt-in only */
  --pl-hairline:      #e0e0e0;   /* Siwa: var(--colors-border)       #e4b68a */
  --pl-scrim:         rgba(0, 0, 0, 0.5);

  /* ── SPACING (measured 5px base, 60.6% fit — Siwa is 4px) ─────────── */
  --pl-space-1:   5px;
  --pl-space-2:  10px;
  --pl-space-3:  15px;
  --pl-space-4:  20px;
  --pl-space-6:  30px;
  --pl-space-8:  40px;
  --pl-space-12: 60px;
  --pl-space-16: 80px;

  /* ── LAYOUT (measured) ────────────────────────────────────────────── */
  --pl-page-max:      1440px;
  --pl-content-max:   1265px;   /* measured carousel/grid container */
  --pl-gutter:        ${carouselGap};
  --pl-header-h:      ${M.header?.h ? Math.round(M.header.h) : 56}px;
  --pl-hero-h:        ${hero?.h ? Math.round(hero.h) : 623}px;

  /* ── SHAPE (measured 0px on 1344 of 1355 elements) ────────────────── */
  --pl-radius: 0px;             /* == var(--rounded-none) — no conflict */

  /* ── TYPE ──────────────────────────────────────────────────────────
     phlur.com serves 'aktiv-grotesk-extended' (display) and 'ABCRepro'
     (body/mono). Both are licensed and are NOT redistributed here.
     Substituted with the families Siwa already licenses. Tracking and
     weight are carried over so the rendered rhythm stays close.
     ─────────────────────────────────────────────────────────────────── */
  --pl-font-display: var(--font-ui-latin, 'Inter', system-ui, sans-serif);
  --pl-font-body:    var(--font-ui-latin, 'Inter', system-ui, sans-serif);
  --pl-font-mono:    var(--font-mono, 'JetBrains Mono', ui-monospace, monospace);

  /* measured type ramp */
  --pl-fs-hero:      ${hero?.heading?.fontSize || '44px'};
  --pl-lh-hero:      ${hero?.heading?.lineHeight || '44px'};
  --pl-ls-hero:      ${hero?.heading?.letterSpacing || '0.96px'};
  --pl-fs-section:   18px;
  --pl-ls-section:   0.96px;
  --pl-fs-card:      14px;
  --pl-ls-card:      0.64px;
  --pl-fs-body:      14px;
  --pl-fs-micro:     ${badge?.fontSize || '11px'};
  --pl-ls-micro:     ${badge?.letterSpacing || '0.7px'};
  --pl-fs-button:    ${btn?.fontSize || '12px'};
  --pl-ls-button:    ${btn?.letterSpacing || '0.8px'};

  /* ── MOTION (measured off the CTA transition) ─────────────────────── */
  --pl-duration: 0.25s;
  --pl-easing:   cubic-bezier(0.8, 0, 0.2, 1);

  /* ── CONTROL SIZING ───────────────────────────────────────────────── */
  --pl-button-h:      ${btn?.h ? Math.round(btn.h) : 40}px;   /* measured */
  --pl-button-pad-i:  30px;                                    /* measured */
  --pl-tap-min:       44px;   /* WCAG 2.2 AA floor — see .pl-button::after */
}

/* Breakpoints measured off phlur.com: max-749 / min-750 / max-989.
   Declared here as documentation; media queries need literals. */
`);

  /* ═══════════════════════════════════════════════════════════════════
     BUTTON
     ═══════════════════════════════════════════════════════════════════ */
  w('assets/component-button.css', `/* Button — measured: ${Math.round(btn?.h || 40)}px tall, padding-inline 30px,
   ${btn?.fontSize} / ${btn?.fontWeight} / ${btn?.letterSpacing} / uppercase,
   radius 0, 1px border matching fill, transition ${btn?.transition || '0.25s'} */

.pl-button {
  position: relative;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  block-size: var(--pl-button-h);
  padding-inline: var(--pl-button-pad-i);
  padding-block: 0;

  font-family: var(--pl-font-mono);
  font-size: var(--pl-fs-button);
  font-weight: 500;
  letter-spacing: var(--pl-ls-button);
  text-transform: uppercase;
  text-decoration: none;
  white-space: nowrap;

  border: 1px solid currentColor;
  border-radius: var(--pl-radius);
  cursor: pointer;
  transition: background-color var(--pl-duration) var(--pl-easing),
              color var(--pl-duration) var(--pl-easing),
              border-color var(--pl-duration) var(--pl-easing);
}

/* phlur.com ships a 40px control, which is under the WCAG 2.2 AA 44x44
   target floor. Keep the measured 40px visual box and extend the hit area
   with a transparent pseudo-element — matches Phlur pixel-for-pixel while
   satisfying the Siwa accessibility floor. */
.pl-button::after {
  content: '';
  position: absolute;
  inset-inline: 0;
  inset-block-start: 50%;
  block-size: var(--pl-tap-min);
  transform: translateY(-50%);
}

.pl-button--primary {
  background-color: var(--pl-ink);
  color: var(--pl-ink-inverse);
  border-color: var(--pl-ink);
}
.pl-button--primary:hover {
  background-color: transparent;
  color: var(--pl-ink);
}

/* on-image variant — the hero "SHOP NOW": white fill, black label */
.pl-button--inverse {
  background-color: var(--pl-ink-inverse);
  color: var(--pl-ink);
  border-color: var(--pl-ink-inverse);
}
.pl-button--inverse:hover {
  background-color: transparent;
  color: var(--pl-ink-inverse);
}

.pl-button--ghost {
  background-color: transparent;
  color: var(--pl-ink);
  border-color: var(--pl-ink);
}
.pl-button--ghost:hover {
  background-color: var(--pl-ink);
  color: var(--pl-ink-inverse);
}

.pl-button:focus-visible {
  outline: 2px solid var(--pl-ink);   /* Siwa a11y: 2px solid at 2px offset */
  outline-offset: 2px;
}

.pl-button[aria-disabled='true'],
.pl-button:disabled {
  opacity: 0.4;
  pointer-events: none;
}

@media (prefers-reduced-motion: reduce) {
  .pl-button { transition: none; }
}
`);

  /* ═══════════════════════════════════════════════════════════════════
     BADGE STAMP
     ═══════════════════════════════════════════════════════════════════ */
  w('assets/component-badge-stamp.css', `/* Badge stamp — measured: ${Math.round(badge?.h || 19)}px tall,
   padding ${badge?.padding}, ${badge?.fontSize} / ${badge?.fontWeight} /
   ${badge?.letterSpacing} uppercase, white fill on black ink, radius 0.
   Maps to Siwa 'badge-stamp'. */

.pl-badge {
  display: inline-flex;
  align-items: center;
  padding-block: 4px;
  padding-inline: 6px;

  font-family: var(--pl-font-mono);
  font-size: var(--pl-fs-micro);
  font-weight: 500;
  line-height: 1;
  letter-spacing: var(--pl-ls-micro);
  text-transform: uppercase;

  background-color: var(--pl-surface-alt);
  color: var(--pl-ink);
  border-radius: var(--pl-radius);
  white-space: nowrap;
}

.pl-badge--ink    { background-color: var(--pl-ink);   color: var(--pl-ink-inverse); }
.pl-badge--outline{ background-color: transparent; box-shadow: none; border: 1px solid var(--pl-ink); }

/* positioned over card media */
.pl-badge-slot {
  position: absolute;
  inset-block-start: var(--pl-space-2);
  inset-inline-start: var(--pl-space-2);
  z-index: 2;
  display: flex;
  gap: var(--pl-space-1);
}
`);

  /* ═══════════════════════════════════════════════════════════════════
     PRODUCT CARD
     ═══════════════════════════════════════════════════════════════════ */
  w('assets/component-product-card.css', `/* Product card — measured: ${Math.round(card?.w || 300)}x${Math.round(card?.h || 420)},
   media 1:1 on ${rgbToHex(card?.imageWrapperBg || '#f5f5f5')}, radius 0, no shadow.
   Title 14px/600 uppercase 0.64px tracking. Maps to Siwa 'product-card'. */

.pl-card {
  display: flex;
  flex-direction: column;
  background-color: transparent;
  border-radius: var(--pl-radius);
  box-shadow: none;              /* Siwa rule 4 + measured 'none' */
  text-decoration: none;
  color: inherit;
}

.pl-card__media {
  position: relative;
  aspect-ratio: 1 / 1;           /* measured ${card?.imageBox?.ratio ?? 1} */
  overflow: hidden;
  background-color: var(--pl-surface);
  border-radius: var(--pl-radius);
}

.pl-card__image {
  inline-size: 100%;
  block-size: 100%;
  object-fit: contain;
  display: block;
  transition: transform var(--pl-duration) var(--pl-easing);
}
.pl-card:hover .pl-card__image { transform: scale(1.03); }

.pl-card__body {
  padding-block-start: var(--pl-space-3);
  display: flex;
  flex-direction: column;
  gap: var(--pl-space-1);
  text-align: start;             /* logical — survives RTL */
}

.pl-card__title {
  font-family: var(--pl-font-display);
  font-size: var(--pl-fs-card);
  font-weight: 600;
  letter-spacing: var(--pl-ls-card);
  text-transform: uppercase;
  color: var(--pl-ink);
  margin: 0;
}

.pl-card__subtitle {
  font-family: var(--pl-font-body);
  font-size: var(--pl-fs-body);
  font-weight: 400;
  color: var(--pl-ink-muted);
  margin: 0;
}

/* Siwa rule 6: price is never gold — always ink. */
.pl-card__price {
  font-family: var(--pl-font-body);
  font-size: var(--pl-fs-body);
  color: var(--pl-ink);
  margin: 0;
}
.pl-card__price--sale { color: var(--pl-ink); }
.pl-card__price del   { color: var(--pl-ink-muted); margin-inline-end: var(--pl-space-1); }

.pl-card:focus-visible { outline: 2px solid var(--pl-ink); outline-offset: 2px; }

@media (prefers-reduced-motion: reduce) {
  .pl-card__image { transition: none; }
  .pl-card:hover .pl-card__image { transform: none; }
}
`);

  /* ═══════════════════════════════════════════════════════════════════
     HERO BANNER
     ═══════════════════════════════════════════════════════════════════ */
  w('assets/section-hero-banner.css', `/* Hero banner — measured ${Math.round(hero?.h || 623)}px tall, full-bleed media,
   content block-end/inline-start, heading ${hero?.heading?.fontSize} /
   ${hero?.heading?.weight} uppercase ${hero?.heading?.letterSpacing},
   single CTA (measured ctaCount=${hero?.ctaCount ?? 1} — satisfies Siwa principle 1). */

.pl-hero {
  position: relative;
  inline-size: 100%;
  min-block-size: var(--pl-hero-h);
  display: grid;
  overflow: hidden;
  background-color: var(--pl-ink);
}

.pl-hero__media,
.pl-hero__media img,
.pl-hero__media video {
  grid-area: 1 / 1;
  inline-size: 100%;
  block-size: 100%;
  object-fit: cover;
  display: block;
}

/* legibility scrim — only over the text side, so the product stays clean */
.pl-hero__scrim {
  grid-area: 1 / 1;
  background: linear-gradient(
    to top,
    rgba(0, 0, 0, 0.55) 0%,
    rgba(0, 0, 0, 0.25) 35%,
    rgba(0, 0, 0, 0) 65%
  );
}

.pl-hero__content {
  grid-area: 1 / 1;
  position: relative;
  z-index: 1;
  align-self: end;
  justify-self: start;
  max-inline-size: 640px;
  padding-inline: var(--pl-space-16);
  padding-block-end: var(--pl-space-16);
  text-align: start;
}

.pl-hero--center .pl-hero__content { justify-self: center; text-align: center; }
.pl-hero--end    .pl-hero__content { justify-self: end; }

.pl-hero__heading {
  font-family: var(--pl-font-display);
  font-size: var(--pl-fs-hero);
  line-height: var(--pl-lh-hero);
  font-weight: 600;
  letter-spacing: var(--pl-ls-hero);
  text-transform: uppercase;
  color: var(--pl-ink-inverse);
  margin: 0 0 var(--pl-space-3);
}

.pl-hero__subheading {
  font-family: var(--pl-font-body);
  font-size: 16px;
  font-weight: 400;
  color: var(--pl-ink-inverse);
  margin: 0 0 var(--pl-space-4);
  /* phlur.com sets this line on a single row at 533px. 60ch keeps that at
     Inter's metrics without letting long copy run the full 640px box. */
  max-inline-size: 60ch;
}

.pl-hero--dark .pl-hero__heading,
.pl-hero--dark .pl-hero__subheading { color: var(--pl-ink); }

@media (max-width: 989px) {
  .pl-hero__content { padding-inline: var(--pl-space-8); padding-block-end: var(--pl-space-8); }
}

@media (max-width: 749px) {
  .pl-hero { min-block-size: 480px; }
  .pl-hero__content { padding-inline: var(--pl-space-4); padding-block-end: var(--pl-space-6); }
  .pl-hero__heading { font-size: 30px; line-height: 32px; }
}
`);

  /* ═══════════════════════════════════════════════════════════════════
     PRODUCT CAROUSEL
     ═══════════════════════════════════════════════════════════════════ */
  w('assets/section-product-carousel.css', `/* Product carousel — measured: flex, gap ${carouselGap}, overflow-x auto,
   container 1265px, ~4.2 cards visible at 1440. Heading 18px/600 uppercase. */

.pl-carousel {
  padding-block: var(--pl-space-12);
  background-color: var(--pl-bg);
}

.pl-carousel__inner {
  max-inline-size: var(--pl-content-max);
  margin-inline: auto;
  padding-inline: var(--pl-space-4);
}

.pl-carousel__head {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  gap: var(--pl-space-4);
  margin-block-end: var(--pl-space-4);
}

.pl-carousel__title {
  font-family: var(--pl-font-display);
  font-size: var(--pl-fs-section);
  font-weight: 600;
  letter-spacing: var(--pl-ls-section);
  text-transform: uppercase;
  color: var(--pl-ink);
  margin: 0;
}

.pl-carousel__link {
  font-family: var(--pl-font-body);
  font-size: var(--pl-fs-body);
  color: var(--pl-ink);
  text-decoration: underline;
  text-underline-offset: 3px;
  white-space: nowrap;
}
.pl-carousel__link:focus-visible { outline: 2px solid var(--pl-ink); outline-offset: 2px; }

.pl-carousel__track {
  display: flex;
  gap: var(--pl-gutter);
  list-style: none;
  margin: 0;
  padding-inline: 0;
  overflow-x: auto;
  scroll-snap-type: x mandatory;
  scroll-behavior: smooth;
  -webkit-overflow-scrolling: touch;
  scrollbar-width: none;
  padding-block-end: var(--pl-space-1);
}
.pl-carousel__track::-webkit-scrollbar { display: none; }

.pl-carousel__item {
  flex: 0 0 auto;
  inline-size: ${Math.round(card?.w || 300)}px;   /* measured */
  scroll-snap-align: start;
}

@media (max-width: 989px) {
  .pl-carousel__item { inline-size: 260px; }
}
@media (max-width: 749px) {
  .pl-carousel        { padding-block: var(--pl-space-8); }
  .pl-carousel__item  { inline-size: 62vw; }
  .pl-carousel__inner { padding-inline: var(--pl-space-3); }
}

@media (prefers-reduced-motion: reduce) {
  .pl-carousel__track { scroll-behavior: auto; }
}
`);

  /* ═══════════════════════════════════════════════════════════════════
     COLLECTION GRID / EDITORIAL / PRODUCT GRID
     ═══════════════════════════════════════════════════════════════════ */
  w('assets/section-collection-grid.css', `/* Collection grid + generic product grid.
   Measured: 3-up collection tiles, 4-up product grid at 1440. */

.pl-grid-section {
  padding-block: var(--pl-space-12);
  background-color: var(--pl-bg);
}
.pl-grid-section__inner {
  max-inline-size: var(--pl-content-max);
  margin-inline: auto;
  padding-inline: var(--pl-space-4);
}
.pl-grid-section__title {
  font-family: var(--pl-font-display);
  font-size: var(--pl-fs-section);
  font-weight: 600;
  letter-spacing: var(--pl-ls-section);
  text-transform: uppercase;
  color: var(--pl-ink);
  margin: 0 0 var(--pl-space-4);
}

.pl-grid {
  display: grid;
  gap: var(--pl-gutter);
  grid-template-columns: repeat(var(--pl-grid-cols, 4), minmax(0, 1fr));
}
.pl-grid--3 { --pl-grid-cols: 3; }
.pl-grid--2 { --pl-grid-cols: 2; }

.pl-tile {
  position: relative;
  display: block;
  aspect-ratio: 3 / 4;
  overflow: hidden;
  background-color: var(--pl-surface);
  border-radius: var(--pl-radius);
  text-decoration: none;
}
.pl-tile img {
  inline-size: 100%; block-size: 100%;
  object-fit: cover; display: block;
  transition: transform var(--pl-duration) var(--pl-easing);
}
.pl-tile:hover img { transform: scale(1.04); }
.pl-tile__label {
  position: absolute;
  inset-block-end: var(--pl-space-4);
  inset-inline-start: var(--pl-space-4);
  font-family: var(--pl-font-display);
  font-size: var(--pl-fs-card);
  font-weight: 600;
  letter-spacing: var(--pl-ls-card);
  text-transform: uppercase;
  color: var(--pl-ink-inverse);
}
.pl-tile:focus-visible { outline: 2px solid var(--pl-ink); outline-offset: 2px; }

@media (max-width: 989px) { .pl-grid { --pl-grid-cols: 2; } }
@media (max-width: 749px) {
  .pl-grid { --pl-grid-cols: 2; gap: var(--pl-space-2); }
  .pl-grid-section { padding-block: var(--pl-space-8); }
}

@media (prefers-reduced-motion: reduce) {
  .pl-tile img { transition: none; }
  .pl-tile:hover img { transform: none; }
}
`);

  w('assets/section-editorial.css', `/* Editorial / quote strip — measured 200px tall, centered, on --pl-bg. */

.pl-editorial {
  padding-block: var(--pl-space-12);
  background-color: var(--pl-bg);
  text-align: center;
}
.pl-editorial__inner {
  max-inline-size: 800px;      /* measured max-width 800px */
  margin-inline: auto;
  padding-inline: var(--pl-space-4);
}
.pl-editorial__quote {
  font-family: var(--pl-font-display);
  font-size: 28px;
  line-height: 1.25;
  font-weight: 400;
  color: var(--pl-ink);
  margin: 0 0 var(--pl-space-3);
}
.pl-editorial__attribution {
  font-family: var(--pl-font-mono);
  font-size: var(--pl-fs-micro);
  letter-spacing: var(--pl-ls-micro);
  text-transform: uppercase;
  color: var(--pl-ink-muted);
  margin: 0;
}
.pl-editorial--dark {
  background-color: var(--pl-ink);
}
.pl-editorial--dark .pl-editorial__quote { color: var(--pl-ink-inverse); }

@media (max-width: 749px) {
  .pl-editorial__quote { font-size: 20px; }
  .pl-editorial { padding-block: var(--pl-space-8); }
}
`);

  /* ═══════════════════════════════════════════════════════════════════
     HEADER
     ═══════════════════════════════════════════════════════════════════ */
  w('assets/section-site-header.css', `/* Header — measured ${M.header?.h ? Math.round(M.header.h) : 56}px, transparent over hero,
   13px nav links, sentence case. Announcement bar 36px above it. */

.pl-announce {
  background-color: var(--pl-ink);
  color: var(--pl-ink-inverse);
  min-block-size: 36px;         /* measured */
  display: flex;
  align-items: center;
  justify-content: center;
  font-family: var(--pl-font-mono);
  font-size: var(--pl-fs-micro);
  letter-spacing: var(--pl-ls-micro);
  text-transform: uppercase;
  padding-inline: var(--pl-space-4);
  text-align: center;
}
.pl-announce a { color: inherit; }

.pl-header {
  position: sticky;
  inset-block-start: 0;
  z-index: 100;                  /* Siwa z-scale */
  block-size: var(--pl-header-h);
  display: flex;
  align-items: center;
  background-color: var(--pl-bg);
  border-block-end: 1px solid var(--pl-hairline);
}
.pl-header--transparent {
  background-color: transparent;
  border-block-end: none;
  color: var(--pl-ink-inverse);
}

.pl-header__inner {
  inline-size: 100%;
  max-inline-size: var(--pl-page-max);
  margin-inline: auto;
  padding-inline: var(--pl-space-4);
  display: grid;
  grid-template-columns: 1fr auto 1fr;
  align-items: center;
  gap: var(--pl-space-4);
}

.pl-header__nav {
  display: flex;
  align-items: center;
  gap: var(--pl-space-4);
}
.pl-header__nav a {
  font-family: var(--pl-font-body);
  font-size: 13px;               /* measured */
  color: currentColor;
  text-decoration: none;
}
.pl-header__nav a:hover { text-decoration: underline; text-underline-offset: 3px; }
.pl-header__nav a:focus-visible { outline: 2px solid currentColor; outline-offset: 2px; }

.pl-header__logo {
  justify-self: center;
  font-family: var(--pl-font-display);
  font-weight: 600;
  letter-spacing: 2px;
  text-transform: uppercase;
  text-decoration: none;
  color: currentColor;
  font-size: 18px;
}
.pl-header__logo img { block-size: 22px; inline-size: auto; display: block; }

.pl-header__actions {
  justify-self: end;
  display: flex;
  align-items: center;
  gap: var(--pl-space-3);
}
.pl-header__actions a,
.pl-header__actions button {
  color: currentColor;
  background: none;
  border: 0;
  cursor: pointer;
  font-family: var(--pl-font-body);
  font-size: 13px;
  min-inline-size: var(--pl-tap-min);
  min-block-size: var(--pl-tap-min);
  display: inline-flex;
  align-items: center;
  justify-content: center;
}

.pl-header__burger { display: none; }

@media (max-width: 989px) {
  .pl-header__nav   { display: none; }
  .pl-header__burger{ display: inline-flex; }
  .pl-header__inner { grid-template-columns: auto 1fr auto; }
  .pl-header__logo  { justify-self: start; }
}
`);

  /* ═══════════════════════════════════════════════════════════════════
     FOOTER
     ═══════════════════════════════════════════════════════════════════ */
  w('assets/section-site-footer.css', `/* Footer — measured ${Math.round(489)}px, dark. Uses Siwa surface-dark semantics. */

.pl-footer {
  background-color: var(--pl-ink);
  color: var(--pl-ink-inverse);
  padding-block: var(--pl-space-12) var(--pl-space-6);
}
.pl-footer__inner {
  max-inline-size: var(--pl-content-max);
  margin-inline: auto;
  padding-inline: var(--pl-space-4);
  display: grid;
  grid-template-columns: 2fr repeat(3, 1fr);
  gap: var(--pl-space-8);
}
.pl-footer__title {
  font-family: var(--pl-font-mono);
  font-size: var(--pl-fs-micro);
  letter-spacing: var(--pl-ls-micro);
  text-transform: uppercase;
  margin: 0 0 var(--pl-space-3);
  color: var(--pl-ink-inverse);
}
.pl-footer__list { list-style: none; margin: 0; padding: 0; display: grid; gap: var(--pl-space-2); }
.pl-footer__list a {
  font-family: var(--pl-font-body);
  font-size: var(--pl-fs-body);
  color: var(--pl-ink-inverse);
  text-decoration: none;
  opacity: 0.8;
}
.pl-footer__list a:hover { opacity: 1; text-decoration: underline; text-underline-offset: 3px; }
.pl-footer__list a:focus-visible { outline: 2px solid var(--pl-ink-inverse); outline-offset: 2px; }

.pl-footer__signup { display: flex; gap: 0; margin-block-start: var(--pl-space-3); }
.pl-footer__signup input {
  flex: 1 1 auto;
  block-size: var(--pl-tap-min);
  padding-inline: var(--pl-space-3);
  background: transparent;
  border: 1px solid var(--pl-ink-inverse);
  border-radius: var(--pl-radius);
  color: var(--pl-ink-inverse);
  font-family: var(--pl-font-body);
  font-size: var(--pl-fs-body);
}
.pl-footer__signup input::placeholder { color: var(--pl-ink-inverse); opacity: 0.6; }
.pl-footer__signup input:focus-visible { outline: 2px solid var(--pl-ink-inverse); outline-offset: 2px; }

.pl-footer__bottom {
  max-inline-size: var(--pl-content-max);
  margin-inline: auto;
  padding-inline: var(--pl-space-4);
  margin-block-start: var(--pl-space-8);
  padding-block-start: var(--pl-space-4);
  border-block-start: 1px solid rgba(255, 255, 255, 0.2);
  display: flex;
  justify-content: space-between;
  gap: var(--pl-space-4);
  font-family: var(--pl-font-mono);
  font-size: var(--pl-fs-micro);
  letter-spacing: var(--pl-ls-micro);
  text-transform: uppercase;
  opacity: 0.7;
}

@media (max-width: 989px) { .pl-footer__inner { grid-template-columns: 1fr 1fr; } }
@media (max-width: 749px) {
  .pl-footer__inner  { grid-template-columns: 1fr; gap: var(--pl-space-6); }
  .pl-footer__bottom { flex-direction: column; }
}
`);

  /* ═══════════════════════════════════════════════════════════════════
     PDP
     ═══════════════════════════════════════════════════════════════════ */
  w('assets/section-main-product.css', `/* PDP — two-column: sticky media rail + buy column. */

.pl-pdp {
  max-inline-size: var(--pl-page-max);
  margin-inline: auto;
  padding-inline: var(--pl-space-4);
  padding-block: var(--pl-space-8);
  display: grid;
  grid-template-columns: minmax(0, 1.15fr) minmax(0, 1fr);
  gap: var(--pl-space-12);
  align-items: start;
}

.pl-pdp__media { display: grid; gap: var(--pl-space-2); }
.pl-pdp__media figure { margin: 0; background-color: var(--pl-surface); aspect-ratio: 1 / 1; }
.pl-pdp__media img { inline-size: 100%; block-size: 100%; object-fit: contain; display: block; }

.pl-pdp__info { position: sticky; inset-block-start: calc(var(--pl-header-h) + var(--pl-space-4)); }

.pl-pdp__title {
  font-family: var(--pl-font-display);
  font-size: 28px;
  font-weight: 600;
  letter-spacing: var(--pl-ls-section);
  text-transform: uppercase;
  color: var(--pl-ink);
  margin: 0 0 var(--pl-space-2);
}
.pl-pdp__subtitle {
  font-family: var(--pl-font-body);
  font-size: 16px;
  color: var(--pl-ink-muted);
  margin: 0 0 var(--pl-space-4);
}
.pl-pdp__price {
  font-family: var(--pl-font-body);
  font-size: 18px;
  color: var(--pl-ink);          /* Siwa rule 6: never gold */
  margin: 0 0 var(--pl-space-4);
}

.pl-pdp__variants { display: flex; flex-wrap: wrap; gap: var(--pl-space-2); margin-block-end: var(--pl-space-4); }
.pl-pdp__variant {
  min-block-size: var(--pl-tap-min);
  min-inline-size: var(--pl-tap-min);
  padding-inline: var(--pl-space-3);
  display: inline-flex; align-items: center; justify-content: center;
  border: 1px solid var(--pl-hairline);
  border-radius: var(--pl-radius);
  background: transparent;
  font-family: var(--pl-font-mono);
  font-size: var(--pl-fs-micro);
  letter-spacing: var(--pl-ls-micro);
  text-transform: uppercase;
  cursor: pointer;
}
.pl-pdp__variant[aria-checked='true'] { border-color: var(--pl-ink); background: var(--pl-ink); color: var(--pl-ink-inverse); }
.pl-pdp__variant:focus-visible { outline: 2px solid var(--pl-ink); outline-offset: 2px; }

.pl-pdp__atc { inline-size: 100%; }

.pl-pdp__accordion { margin-block-start: var(--pl-space-6); border-block-start: 1px solid var(--pl-hairline); }
.pl-pdp__accordion details { border-block-end: 1px solid var(--pl-hairline); }
.pl-pdp__accordion summary {
  cursor: pointer;
  list-style: none;
  padding-block: var(--pl-space-3);
  min-block-size: var(--pl-tap-min);
  display: flex; align-items: center; justify-content: space-between;
  font-family: var(--pl-font-mono);
  font-size: var(--pl-fs-micro);
  letter-spacing: var(--pl-ls-micro);
  text-transform: uppercase;
  color: var(--pl-ink);
}
.pl-pdp__accordion summary::-webkit-details-marker { display: none; }
.pl-pdp__accordion summary::after { content: '+'; font-size: 16px; }
.pl-pdp__accordion details[open] summary::after { content: '\\2212'; }
.pl-pdp__accordion .pl-pdp__panel {
  padding-block-end: var(--pl-space-4);
  font-family: var(--pl-font-body);
  font-size: var(--pl-fs-body);
  color: var(--pl-ink-muted);
  line-height: 1.6;
}

@media (max-width: 989px) {
  .pl-pdp { grid-template-columns: 1fr; gap: var(--pl-space-6); }
  .pl-pdp__info { position: static; }
}
`);

  return { files, dirs, spec: { btn, badge, card, hero, carouselGap } };
}
